base_url = "https://example.com"
build_search_index = false
compile_sass = false
default_language = "en"

languages = [
    {code = "no"},
]

[markdown]
highlight_code = false

[translations]
[translations.en]
title = "Yngve Hoiseth"

[translations.no]
title = "Yngve Høiseth"

[extra]
# Put all your custom variables here
